import { ThemeModeScript } from "flowbite-react";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/footer/footer";
import NavigationBar from "@/components/navigation-bar/navigation-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript></ThemeModeScript>
      </head>
      <body className={inter.className}>
        <NavigationBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
